security:
  user:
    name: user
    password: password

broker:
  namespace: root/celerra
  managementProvider: https://10.243.105.115:5989/emc/cimnas
  port: 5989
  SSLEnabled: true
  username: nasadmin
  password: nasadmin
  fileSystemId: 00019710012400016



         
          
